SurveyFilesWebChecker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),
    # url(r'^accounts/signup/$', views.signup, name='signup'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
    url('surveyfiles/', include('surveyfiles.urls', namespace='surveyfiles')),
    url(r'api-auth/', include('rest_framework.urls')),
    url(r'rest-auth/', include('rest_auth.urls')),
    url('surveyfiles/api/', include('surveyfiles.api.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

surveyfiles/urls.py
from django.conf.urls import url, include

from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url('^list/', SurveyFilesListFilterView.as_view(), name='jxl_list_view'),
    url('^cards/', SurveyFilesCardsFilterView.as_view(), name='jxl_cards_view'),
    url(r'^details/(?P<pk>[\w\-]+)/$', SurveyFileDetailView.as_view(), name='details_view'),
    url('^sketch-setup/', login_required(JobSetUpView.as_view()), name='sketch_pdf_setup_view'),
    url('^data-export/', login_required(DataExportView.as_view()), name='data_export_view'),
    url('upload/', login_required(CreateSurveyFileAutomationView.as_view()), name='jxl_create_view'),
    url('ppp_automation/', login_required(CreatePPPFileAutomationView.as_view()), name='ppp_automation_view'),
]

templates/_pagination_short.html
{% load i18n %}
<div class="pagination" style="font-size: medium">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page" style="color: indianred ; font-size: larger; font-weight: bolder">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

templates/base.html
{% load staticfiles %}

<!doctype html>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

    {% block scripts %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>


</head>
{% include 'navigator.html' %}
<body>

<div class="content-section">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load auth_extras %}

{% block title %}Home{% endblock %}

{% block content %}
    <!--<div id="navigation_links">-->
    <!--{% if request.user.is_authenticated %}-->
        <!--{% if request.user.first_name %}-->
            <!--<p class="hello-word">Hi {{ request.user.first_name }}! You are logged in !</p>-->
            <!--{% else %}-->
            <!--<p class="hello-word">Hi {{ request.user.username }}! You are logged in !</p>-->
            <!--{% endif %}-->

        <!--{% if request.user.is_superuser %}-->
            <!--<p>Other Users Logged in: {{ current_users }} </p>-->
            <!--{% endif %}-->
        <!--{% endif %}-->
    <!--</div>-->
    <div class="huge-button-div">

        <div style="text-align: center">
            <a class="huge-button" href="{% url 'surveyfiles:jxl_create_view' %}">JXL Validation (for Surveyors)</a>
        </div>

        <div style="text-align: center">
            <a class="huge-button" href="{% url 'surveyfiles:sketch_pdf_setup_view' %}">Job Sketch PDF Set Up</a>
        </div>

        <div style="text-align: center">
            <a class="huge-button" href="{% url 'surveyfiles:data_export_view' %}">Data Exporting</a>
        </div>


        {% if request.user.is_superuser %}
            <div style="text-align: center">
                <a class="huge-button" href="{% url 'surveyfiles:jxl_list_view' %}">Automation List</a>
            </div>
        {% endif %}

        <div style="text-align: center">
            <a class="huge-button" href="{% url 'surveyfiles:jxl_cards_view' %}">Automation Cards - Check Status</a>
        </div>

        {#        {% if request.user|is_ppp_automation_group or request.user.is_superuser %}#}
        <div style="text-align: center">
            <a class="huge-button" href="{% url 'surveyfiles:ppp_automation_view' %}">Create Transmittals (for PM)</a>
        </div>
        {#        {% endif %}#}

    </div>
{% endblock %}

templates/navigator.html
<!-- Top navigation -->
<div class="topnav">

    <!-- Centered link -->
    <div class="topnav-centered">
        {% if user.is_authenticated %}
            <!--{% if request.user.first_name %}-->
                <!--<a class="navbar-brand" href="{% url 'home' %}">Hi, {{ request.user.first_name }} ! Welcome to JXL Uploading Web !</a>-->
                <!--{% else %}-->
                <!--<a class="navbar-brand" href="{% url 'home' %}">Hi, {{ request.user }} ! Welcome to JXL Uploading Web !</a>-->
                <!--{% endif %}-->
            <a class="navbar-brand navbar-web-title" href="{% url 'home' %}">{{ request.user.first_name }} - {{ web_title }}</a>
        {% else %}
            <a class="navbar-brand navbar-web-title" href="{% url 'home' %}">{{ web_title }}</a>
        {% endif %}
    </div>

    <!-- Left-aligned links (default) -->
    <a href="{% url 'home' %}">Home</a>

    {% if request.user.is_superuser %}
        <a href="{% url 'admin:index' %}" target="_blank">Admin</a>
    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Log Out</a>
    {% else %}
        <a href="{% url 'login' %}">Log In</a>
{#        <a href="{% url 'signup' %}">Sign Up</a>#}
    {% endif %}

    {#  <!-- Right-aligned links -->#}
    {#
    <div class="topnav-right">#}
        {# <a href="#search">Search</a>#}
        {# <a href="#about">About</a>#}
        {#
    </div>
    #}

    <!-- Right-aligned links -->
    <div class="topnav-right">
        <a class="btn btn-primary"
           style="color: yellow; font-weight: bolder;margin-bottom: 2pt; height: 80%; text-align: center"
           href="mailto:jxue@globalraymac.ca?subject=Questions about GIS Web">Contact Jason Xue!</a>
    </div>
</div>